### ISSUE TITLE
Display decision tree widget shows an error

### ISSUE THREAD

**Issue by matejMartinc** [xflows/clowdflows#14]
The widget "Display decision tree" from the ScikitAlgorithms category shows a "Permission denied" error. The workflow that I am trying to run is shown in the attached image.
![displ_dec_tree](https://cloud.githubusercontent.com/assets/5680497/23072114/dc0015b4-f530-11e6-87ed-ff8d4f4e815a.jpeg)

**Comment by daleksovski** [comment]
Thanks @matejMartinc for reporting this. It should be fixed now.
