### ISSUE TITLE
Streaming Triplet graph doesn't show any data

### ISSUE THREAD

**Issue by RaulEstrada** [xflows/clowdflows#19]
Hello, I created a stream mining workflow with the RSS Reader widget, the Summarize news article widget, Triplet extraction widget, Wordnet Lemmatizer widget, sliding window and Streaming Triplet graph widget. 
I was following the example displayed in the "_ClowdFlows: Online workflows for distributed big data mining_" article, and copied the workflow created by the user _janez_. The workflow is supposed to generate a graph with words from the most important sentences in the news articles, and show how they are linked to each other via the triplets. However, when I start the stream the graph is empty and it never gets updated with new elements.

![rss_workflow](https://cloud.githubusercontent.com/assets/6322230/24192844/a2f45f76-0ef0-11e7-8461-2c320515c861.png)

When I start the stream mining process, no results are displayed. My public workflow is available here: [http://clowdflows.org/workflow/9923/](http://clowdflows.org/workflow/9923/) and the page with the empty graph is available here: [http://clowdflows.org/streams/data/161/97519/](http://clowdflows.org/streams/data/161/97519/). It's the same as the one used in the article. I started the stream mining process a while ago, and since then I know new data has been added to the data source (I'm using the [CNN Middle East RSS](http://rss.cnn.com/rss/edition_meast.rss), but also tried using the Google News RSS).

I added an Object viewer widget in order to see if some final triplets are being generated, and they are. When I run the workflow from the Workflow Editor, the Object viewer shows some results.

![rss_results](https://cloud.githubusercontent.com/assets/6322230/24192906/cfe0c768-0ef0-11e7-94ce-1610a4e2be21.png)

Can anyone give me some idea about how to solve this? Maybe I'm missing some necessary widget or configuration step, but I couldn't find any manual or tutorial about this.

**Comment by janezkranjc** [comment]
I don't think you're doing anything wrong, might be an error! I'll check it
out and let you know!

**Comment by janezkranjc** [comment]
I've located the error - there was a stream that caused the processing deamon to malfunction. Hopefully you should start seeing results soon. There might be a slight delay though (as there's loads of stream that are being processed).

**Comment by janezkranjc** [comment]
I'm also gonna check back after a while to see that it really is working.

**Comment by RaulEstrada** [comment]
It is working. I can see new data in the graph now.
Thank you.
