### ISSUE TITLE
Django 2 upgrade?

### ISSUE THREAD

**Issue by brylie** [xflows/clowdflows#22]
What are the plans for upgrading this project to use Django 2?

I would like to help with the task. Is there an existing checklist/roadmap?

**Comment by brylie** [comment]
Hello. I'm just checking up on this issue, as there has been "radio silence" for over a year. Any idea about a Django 2 upgrade?

**Comment by janezkranjc** [comment]
Same answer here :) Check out these two repos:

https://github.com/xflows/clowdflows-backend
https://github.com/xflows/clowdflows-webapp

**Comment by janezkranjc** [comment]
That one still isn't on django 2, but should be much easier to port

**Comment by brylie** [comment]
K, thanks. It might be useful to put a deprecation notice in this project's README, with links to the newer projects. 😀
