### ISSUE TITLE
How add new Weka algorithms to ClowdFlows

### ISSUE THREAD

**Issue by lqdominguez** [xflows/clowdflows#3]
Hello, I need to add some Weka algorithms to ClowdFlows but I haven't found any tutorial about that. Can anyone give me some idea about how I can add Weka algorithms to ClowdFlows.

**Comment by janezkranjc** [comment]
Hello!

I've updated the wiki a bit - you might want to look at it:

https://github.com/janezkranjc/clowdflows/wiki
